export type OrderStatus = "PLACED" | "PREPARING" | "COMPLETED";

export interface OrderItem {
  item_id: string; // references a Food's id
  qty: number;
}

export interface Order {
  id: string;
  store_id: string;
  customer_name: string | null;
  items: OrderItem[];
  total_amount: string;
  status: OrderStatus;
  created_at: string;
  updated_at: string;
}

export interface Food {
  id: string;
  name: string;
  price: string;
  category: string | null;
  image_path: string | null; // e.g. /uploads/xyz.png, null = use default-food.png
  created_at: string;
  updated_at: string;
}

export interface InvoiceConfig {
  store_id: string;
  restaurant_name: string;
  restaurant_address: string;
  gst_number: string;
  qr_image_path: string | null;
  footer_note: string;
  created_at: string;
  updated_at: string;
}

export interface Paginated<T> {
  data: T[];
  pagination: {
    page: number;
    limit: number;
    total: number;
    total_pages: number;
  };
}

export const ORDER_STATUSES: OrderStatus[] = ["PLACED", "PREPARING", "COMPLETED"];

// Shown whenever a food item has no uploaded image. The actual file is
// not generated by this codebase - drop it into frontend/public/ later.
export const DEFAULT_FOOD_IMAGE = "/default-food.png";
export const DEFAULT_INVOICE_QR_IMAGE = "/QR.png";
export const DEFAULT_INVOICE_FOOTER_NOTE = "Thanks! Visit Again";
